// src/Resume/components/Job.tsx
import InlineList from "./InlineList";
import styles from "./Job.module.css";
import SubSection from "./SubSection";

export interface JobProps {
  title: string;
  company: string;
  startDate: string;
  endDate?: string;
  description: string;
  technologies: string[];
  children?: React.ReactNode;
}

function Job({
  title,
  company,
  children,
  startDate,
  endDate,
  description,
  technologies,
}: JobProps) {
  return (
    <SubSection
      title={
        <>
          <span className={styles.title}>{title}</span>
          <span> – </span>
          <span className={styles.company}>{company}</span>
          <span className={styles.date}>
            ({startDate} - {endDate ?? "Present"})
          </span>
        </>
      }
      className={styles.job}
    >
      <p>{description}</p>
      {children}
      <InlineList>
        {technologies.map((tech) => (
          <li>{tech}</li>
        ))}
      </InlineList>
    </SubSection>
  );
}

export default Job;

// src/components/Job.svelte
<script lang="ts">
	import SubSection from './SubSection.svelte';
	import DottedList from './DottedList.svelte';

	export let title: string;
	export let company: string;
	export let startDate: string;
	export let endDate: string | undefined = undefined;
	export let description: string;
	export let technologies: string[];
</script>

<SubSection>
	<svelte:fragment slot="title">
		<span class="title">{title}</span>
		<span> – </span>
		<span class="company">{company}</span>
		<span class="date">
			({startDate} - {endDate ?? 'Present'})
		</span>
	</svelte:fragment>

	<p>{description}</p>

	<DottedList>
		{#each technologies as tech}
			<li>{tech}</li>
		{/each}
	</DottedList>

	{#if $$slots.extra}
		<div class="extra">
			<slot name="extra" />
		</div>
	{/if}
</SubSection>

<style>
	.title,
	.company,
	.date {
		white-space: nowrap;
	}

	.date {
		color: var(--secondary-color);
		font-size: var(--font-sm);
		margin-left: var(--space-xxs);
	}

	.extra {
		margin-top: var(--space-xs);
	}
</style>
